// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package assemble

import "github.com/hawkowl/biscuit/pkg/opcodes"

func EncodeFENCE_I(o opcodes.OP_FENCE_I) (uint32, error) {
	IMM12, err := GEN_IMM12(o.IMM12)
	if err != nil {
		return 0, err
	}
	RS1, err := GEN_RS1(o.RS1)
	if err != nil {
		return 0, err
	}
	RD, err := GEN_RD(o.RD)
	if err != nil {
		return 0, err
	}

	return 0x0000100F | IMM12 | RS1 | RD, nil
}
