// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package assemble

import "github.com/hawkowl/biscuit/pkg/opcodes"

func EncodeMRET(o opcodes.OP_MRET) (uint32, error) {
	return 0x30200073, nil
}

func EncodeDRET(o opcodes.OP_DRET) (uint32, error) {
	return 0x7B200073, nil
}

func EncodeWFI(o opcodes.OP_WFI) (uint32, error) {
	return 0x10500073, nil
}
