// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

const (
	MASK_FENCE_I  uint32 = 0x0000707F
	MATCH_FENCE_I uint32 = 0x0000100F
)

type OP_FENCE_I struct {
	IMM12 int32
	RS1   uint32
	RD    uint32
}

func (o OP_FENCE_I) Components() Components {
	return Components{
		IMM12: o.IMM12,
		RS1:   o.RS1,
		RD:    o.RD,
	}
}
