// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

const (
	MASK_MRET  uint32 = 0xFFFFFFFF
	MATCH_MRET uint32 = 0x30200073
	MASK_DRET  uint32 = 0xFFFFFFFF
	MATCH_DRET uint32 = 0x7B200073
	MASK_WFI   uint32 = 0xFFFFFFFF
	MATCH_WFI  uint32 = 0x10500073
)

type OP_MRET struct {
}

func (o OP_MRET) Components() Components {
	return Components{}
}

type OP_DRET struct {
}

func (o OP_DRET) Components() Components {
	return Components{}
}

type OP_WFI struct {
}

func (o OP_WFI) Components() Components {
	return Components{}
}
