// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

type OP_LUI struct {
	RD    uint32
	IMM20 uint32
}

type OP_AUIPC struct {
	RD    uint32
	IMM20 uint32
}

type OP_JAL struct {
	RD     uint32
	JIMM20 int32
}

type OP_JALR struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_BEQ struct {
	BIMM12 int32
	RS1    uint32
	RS2    uint32
}

type OP_BNE struct {
	BIMM12 int32
	RS1    uint32
	RS2    uint32
}

type OP_BLT struct {
	BIMM12 int32
	RS1    uint32
	RS2    uint32
}

type OP_BGE struct {
	BIMM12 int32
	RS1    uint32
	RS2    uint32
}

type OP_BLTU struct {
	BIMM12 int32
	RS1    uint32
	RS2    uint32
}

type OP_BGEU struct {
	BIMM12 int32
	RS1    uint32
	RS2    uint32
}

type OP_LB struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_LH struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_LW struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_LBU struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_LHU struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_SB struct {
	IMM12 int32
	RS1   uint32
	RS2   uint32
}

type OP_SH struct {
	IMM12 int32
	RS1   uint32
	RS2   uint32
}

type OP_SW struct {
	IMM12 int32
	RS1   uint32
	RS2   uint32
}

type OP_ADDI struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_SLTI struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_SLTIU struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_XORI struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_ORI struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_ANDI struct {
	RD    uint32
	RS1   uint32
	IMM12 int32
}

type OP_ADD struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_SUB struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_SLL struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_SLT struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_SLTU struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_XOR struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_SRL struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_SRA struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_OR struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_AND struct {
	RD  uint32
	RS1 uint32
	RS2 uint32
}

type OP_FENCE struct {
	FM   uint32
	PRED uint32
	SUCC uint32
	RS1  uint32
	RD   uint32
}

type OP_ECALL struct {
}

type OP_EBREAK struct {
}

type OP_SLLI struct {
	RD     uint32
	RS1    uint32
	SHAMTW uint32
}

type OP_SRLI struct {
	RD     uint32
	RS1    uint32
	SHAMTW uint32
}

type OP_SRAI struct {
	RD     uint32
	RS1    uint32
	SHAMTW uint32
}
