// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

const (
	MASK_CSRRW   uint32 = 0x0000707F
	MATCH_CSRRW  uint32 = 0x00001073
	MASK_CSRRS   uint32 = 0x0000707F
	MATCH_CSRRS  uint32 = 0x00002073
	MASK_CSRRC   uint32 = 0x0000707F
	MATCH_CSRRC  uint32 = 0x00003073
	MASK_CSRRWI  uint32 = 0x0000707F
	MATCH_CSRRWI uint32 = 0x00005073
	MASK_CSRRSI  uint32 = 0x0000707F
	MATCH_CSRRSI uint32 = 0x00006073
	MASK_CSRRCI  uint32 = 0x0000707F
	MATCH_CSRRCI uint32 = 0x00007073
)

type OP_CSRRW struct {
	RD  uint32
	RS1 uint32
	CSR uint32
}

type OP_CSRRS struct {
	RD  uint32
	RS1 uint32
	CSR uint32
}

type OP_CSRRC struct {
	RD  uint32
	RS1 uint32
	CSR uint32
}

type OP_CSRRWI struct {
	RD   uint32
	CSR  uint32
	ZIMM uint32
}

type OP_CSRRSI struct {
	RD   uint32
	CSR  uint32
	ZIMM uint32
}

type OP_CSRRCI struct {
	RD   uint32
	CSR  uint32
	ZIMM uint32
}
