// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

const (
	MASK_SFENCE_VMA  uint32 = 0xFE007FFF
	MATCH_SFENCE_VMA uint32 = 0x12000073
	MASK_SRET        uint32 = 0xFFFFFFFF
	MATCH_SRET       uint32 = 0x10200073
)

type OP_SFENCE_VMA struct {
	RS1 uint32
	RS2 uint32
}

func (o OP_SFENCE_VMA) Components() Components {
	return Components{
		RS1: o.RS1,
		RS2: o.RS2,
	}
}

type OP_SRET struct {
}

func (o OP_SRET) Components() Components {
	return Components{}
}
