// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

type Components struct {
	RD, RS1, RS2                 uint32
	CSR                          uint32
	FM, PRED, SUCC               uint32
	IMM12, BIMM12, JIMM20, IMM20 int32
	ZIMM, SHAMTW                 uint32
}

type Opcode interface {
	Components() Components
	Instruction() string
}

type OP_ILLEGAL struct {
}

func (o OP_ILLEGAL) Components() Components {
	return Components{}
}

func (o OP_ILLEGAL) Instruction() string {
	return "ILLEGAL"
}
