// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package opcodes

type Components struct {
	RD, RS1, RS2          uint32
	CSR                   uint32
	FM, PRED, SUCC        uint32
	IMM12, BIMM12, JIMM20 int32
	ZIMM, IMM20, SHAMTW   uint32
}

type Opcode interface {
	Components() Components
}
