// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package disassemble

import (
	"fmt"
	"strings"

	"github.com/hawkowl/biscuit/pkg/debuginfo"
	"github.com/hawkowl/biscuit/pkg/opcodes"
)

type OP_LUI struct {
	opcodes.OP_LUI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_LUI{}

func (o OP_LUI) String() string {
	return strings.Join([]string{"LUI", o.rd(), o.imm20()}, " ")
}

func (o OP_LUI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_LUI) imm20() string {
	if o.IMM20 == 0 {
		return "imm20=0"
	} else {
		return fmt.Sprintf("imm20=%#x (%d)", uint64(o.IMM20), o.IMM20)
	}
}

func (o OP_LUI) Opcode() opcodes.Opcode {
	return o.OP_LUI
}

func (o OP_LUI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func LUI(RD uint32, IMM20 int32, debug debuginfo.DebugInfo) OP_LUI {

	return OP_LUI{
		OP_LUI: opcodes.OP_LUI{
			RD:    RD,
			IMM20: IMM20,
		},
		debug: debug,
	}
}

func DecodeLUI(inst uint32) OP_LUI {
	r := opcodes.OP_LUI{}

	r.RD = DEC_RD(inst)
	r.IMM20 = DEC_IMM20(inst)
	return OP_LUI{
		OP_LUI: r,
	}
}

type OP_AUIPC struct {
	opcodes.OP_AUIPC
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_AUIPC{}

func (o OP_AUIPC) String() string {
	return strings.Join([]string{"AUIPC", o.rd(), o.imm20()}, " ")
}

func (o OP_AUIPC) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_AUIPC) imm20() string {
	if o.IMM20 == 0 {
		return "imm20=0"
	} else {
		return fmt.Sprintf("imm20=%#x (%d)", uint64(o.IMM20), o.IMM20)
	}
}

func (o OP_AUIPC) Opcode() opcodes.Opcode {
	return o.OP_AUIPC
}

func (o OP_AUIPC) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func AUIPC(RD uint32, IMM20 int32, debug debuginfo.DebugInfo) OP_AUIPC {

	return OP_AUIPC{
		OP_AUIPC: opcodes.OP_AUIPC{
			RD:    RD,
			IMM20: IMM20,
		},
		debug: debug,
	}
}

func DecodeAUIPC(inst uint32) OP_AUIPC {
	r := opcodes.OP_AUIPC{}

	r.RD = DEC_RD(inst)
	r.IMM20 = DEC_IMM20(inst)
	return OP_AUIPC{
		OP_AUIPC: r,
	}
}

type OP_JAL struct {
	opcodes.OP_JAL
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_JAL{}

func (o OP_JAL) String() string {
	return strings.Join([]string{"JAL", o.rd(), o.jimm20()}, " ")
}

func (o OP_JAL) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_JAL) jimm20() string {
	if o.JIMM20 == 0 {
		return "jimm20=0"
	} else {
		return fmt.Sprintf("jimm20=%#x (%d)", uint64(o.JIMM20), o.JIMM20)
	}
}

func (o OP_JAL) Opcode() opcodes.Opcode {
	return o.OP_JAL
}

func (o OP_JAL) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func JAL(RD uint32, JIMM20 int32, debug debuginfo.DebugInfo) OP_JAL {

	return OP_JAL{
		OP_JAL: opcodes.OP_JAL{
			RD:     RD,
			JIMM20: JIMM20,
		},
		debug: debug,
	}
}

func DecodeJAL(inst uint32) OP_JAL {
	r := opcodes.OP_JAL{}

	r.RD = DEC_RD(inst)
	r.JIMM20 = DEC_JIMM20(inst)
	return OP_JAL{
		OP_JAL: r,
	}
}

type OP_JALR struct {
	opcodes.OP_JALR
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_JALR{}

func (o OP_JALR) String() string {
	return strings.Join([]string{"JALR", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_JALR) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_JALR) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_JALR) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_JALR) Opcode() opcodes.Opcode {
	return o.OP_JALR
}

func (o OP_JALR) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func JALR(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_JALR {

	return OP_JALR{
		OP_JALR: opcodes.OP_JALR{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeJALR(inst uint32) OP_JALR {
	r := opcodes.OP_JALR{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_JALR{
		OP_JALR: r,
	}
}

type OP_BEQ struct {
	opcodes.OP_BEQ
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_BEQ{}

func (o OP_BEQ) String() string {
	return strings.Join([]string{"BEQ", o.bimm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_BEQ) bimm12() string {
	if o.BIMM12 == 0 {
		return "bimm12=0"
	} else {
		return fmt.Sprintf("bimm12=%#x (%d)", uint64(o.BIMM12), o.BIMM12)
	}
}

func (o OP_BEQ) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_BEQ) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_BEQ) Opcode() opcodes.Opcode {
	return o.OP_BEQ
}

func (o OP_BEQ) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func BEQ(BIMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_BEQ {

	return OP_BEQ{
		OP_BEQ: opcodes.OP_BEQ{
			BIMM12: BIMM12,
			RS1:    RS1,
			RS2:    RS2,
		},
		debug: debug,
	}
}

func DecodeBEQ(inst uint32) OP_BEQ {
	r := opcodes.OP_BEQ{}

	r.BIMM12 = DEC_BIMM12(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	r.BIMM12 = DEC_BIMM12(inst)
	return OP_BEQ{
		OP_BEQ: r,
	}
}

type OP_BNE struct {
	opcodes.OP_BNE
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_BNE{}

func (o OP_BNE) String() string {
	return strings.Join([]string{"BNE", o.bimm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_BNE) bimm12() string {
	if o.BIMM12 == 0 {
		return "bimm12=0"
	} else {
		return fmt.Sprintf("bimm12=%#x (%d)", uint64(o.BIMM12), o.BIMM12)
	}
}

func (o OP_BNE) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_BNE) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_BNE) Opcode() opcodes.Opcode {
	return o.OP_BNE
}

func (o OP_BNE) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func BNE(BIMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_BNE {

	return OP_BNE{
		OP_BNE: opcodes.OP_BNE{
			BIMM12: BIMM12,
			RS1:    RS1,
			RS2:    RS2,
		},
		debug: debug,
	}
}

func DecodeBNE(inst uint32) OP_BNE {
	r := opcodes.OP_BNE{}

	r.BIMM12 = DEC_BIMM12(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	r.BIMM12 = DEC_BIMM12(inst)
	return OP_BNE{
		OP_BNE: r,
	}
}

type OP_BLT struct {
	opcodes.OP_BLT
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_BLT{}

func (o OP_BLT) String() string {
	return strings.Join([]string{"BLT", o.bimm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_BLT) bimm12() string {
	if o.BIMM12 == 0 {
		return "bimm12=0"
	} else {
		return fmt.Sprintf("bimm12=%#x (%d)", uint64(o.BIMM12), o.BIMM12)
	}
}

func (o OP_BLT) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_BLT) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_BLT) Opcode() opcodes.Opcode {
	return o.OP_BLT
}

func (o OP_BLT) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func BLT(BIMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_BLT {

	return OP_BLT{
		OP_BLT: opcodes.OP_BLT{
			BIMM12: BIMM12,
			RS1:    RS1,
			RS2:    RS2,
		},
		debug: debug,
	}
}

func DecodeBLT(inst uint32) OP_BLT {
	r := opcodes.OP_BLT{}

	r.BIMM12 = DEC_BIMM12(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	r.BIMM12 = DEC_BIMM12(inst)
	return OP_BLT{
		OP_BLT: r,
	}
}

type OP_BGE struct {
	opcodes.OP_BGE
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_BGE{}

func (o OP_BGE) String() string {
	return strings.Join([]string{"BGE", o.bimm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_BGE) bimm12() string {
	if o.BIMM12 == 0 {
		return "bimm12=0"
	} else {
		return fmt.Sprintf("bimm12=%#x (%d)", uint64(o.BIMM12), o.BIMM12)
	}
}

func (o OP_BGE) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_BGE) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_BGE) Opcode() opcodes.Opcode {
	return o.OP_BGE
}

func (o OP_BGE) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func BGE(BIMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_BGE {

	return OP_BGE{
		OP_BGE: opcodes.OP_BGE{
			BIMM12: BIMM12,
			RS1:    RS1,
			RS2:    RS2,
		},
		debug: debug,
	}
}

func DecodeBGE(inst uint32) OP_BGE {
	r := opcodes.OP_BGE{}

	r.BIMM12 = DEC_BIMM12(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	r.BIMM12 = DEC_BIMM12(inst)
	return OP_BGE{
		OP_BGE: r,
	}
}

type OP_BLTU struct {
	opcodes.OP_BLTU
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_BLTU{}

func (o OP_BLTU) String() string {
	return strings.Join([]string{"BLTU", o.bimm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_BLTU) bimm12() string {
	if o.BIMM12 == 0 {
		return "bimm12=0"
	} else {
		return fmt.Sprintf("bimm12=%#x (%d)", uint64(o.BIMM12), o.BIMM12)
	}
}

func (o OP_BLTU) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_BLTU) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_BLTU) Opcode() opcodes.Opcode {
	return o.OP_BLTU
}

func (o OP_BLTU) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func BLTU(BIMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_BLTU {

	return OP_BLTU{
		OP_BLTU: opcodes.OP_BLTU{
			BIMM12: BIMM12,
			RS1:    RS1,
			RS2:    RS2,
		},
		debug: debug,
	}
}

func DecodeBLTU(inst uint32) OP_BLTU {
	r := opcodes.OP_BLTU{}

	r.BIMM12 = DEC_BIMM12(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	r.BIMM12 = DEC_BIMM12(inst)
	return OP_BLTU{
		OP_BLTU: r,
	}
}

type OP_BGEU struct {
	opcodes.OP_BGEU
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_BGEU{}

func (o OP_BGEU) String() string {
	return strings.Join([]string{"BGEU", o.bimm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_BGEU) bimm12() string {
	if o.BIMM12 == 0 {
		return "bimm12=0"
	} else {
		return fmt.Sprintf("bimm12=%#x (%d)", uint64(o.BIMM12), o.BIMM12)
	}
}

func (o OP_BGEU) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_BGEU) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_BGEU) Opcode() opcodes.Opcode {
	return o.OP_BGEU
}

func (o OP_BGEU) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func BGEU(BIMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_BGEU {

	return OP_BGEU{
		OP_BGEU: opcodes.OP_BGEU{
			BIMM12: BIMM12,
			RS1:    RS1,
			RS2:    RS2,
		},
		debug: debug,
	}
}

func DecodeBGEU(inst uint32) OP_BGEU {
	r := opcodes.OP_BGEU{}

	r.BIMM12 = DEC_BIMM12(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	r.BIMM12 = DEC_BIMM12(inst)
	return OP_BGEU{
		OP_BGEU: r,
	}
}

type OP_LB struct {
	opcodes.OP_LB
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_LB{}

func (o OP_LB) String() string {
	return strings.Join([]string{"LB", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_LB) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_LB) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_LB) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_LB) Opcode() opcodes.Opcode {
	return o.OP_LB
}

func (o OP_LB) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func LB(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_LB {

	return OP_LB{
		OP_LB: opcodes.OP_LB{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeLB(inst uint32) OP_LB {
	r := opcodes.OP_LB{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_LB{
		OP_LB: r,
	}
}

type OP_LH struct {
	opcodes.OP_LH
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_LH{}

func (o OP_LH) String() string {
	return strings.Join([]string{"LH", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_LH) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_LH) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_LH) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_LH) Opcode() opcodes.Opcode {
	return o.OP_LH
}

func (o OP_LH) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func LH(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_LH {

	return OP_LH{
		OP_LH: opcodes.OP_LH{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeLH(inst uint32) OP_LH {
	r := opcodes.OP_LH{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_LH{
		OP_LH: r,
	}
}

type OP_LW struct {
	opcodes.OP_LW
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_LW{}

func (o OP_LW) String() string {
	return strings.Join([]string{"LW", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_LW) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_LW) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_LW) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_LW) Opcode() opcodes.Opcode {
	return o.OP_LW
}

func (o OP_LW) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func LW(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_LW {

	return OP_LW{
		OP_LW: opcodes.OP_LW{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeLW(inst uint32) OP_LW {
	r := opcodes.OP_LW{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_LW{
		OP_LW: r,
	}
}

type OP_LBU struct {
	opcodes.OP_LBU
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_LBU{}

func (o OP_LBU) String() string {
	return strings.Join([]string{"LBU", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_LBU) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_LBU) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_LBU) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_LBU) Opcode() opcodes.Opcode {
	return o.OP_LBU
}

func (o OP_LBU) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func LBU(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_LBU {

	return OP_LBU{
		OP_LBU: opcodes.OP_LBU{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeLBU(inst uint32) OP_LBU {
	r := opcodes.OP_LBU{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_LBU{
		OP_LBU: r,
	}
}

type OP_LHU struct {
	opcodes.OP_LHU
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_LHU{}

func (o OP_LHU) String() string {
	return strings.Join([]string{"LHU", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_LHU) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_LHU) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_LHU) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_LHU) Opcode() opcodes.Opcode {
	return o.OP_LHU
}

func (o OP_LHU) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func LHU(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_LHU {

	return OP_LHU{
		OP_LHU: opcodes.OP_LHU{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeLHU(inst uint32) OP_LHU {
	r := opcodes.OP_LHU{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_LHU{
		OP_LHU: r,
	}
}

type OP_SB struct {
	opcodes.OP_SB
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SB{}

func (o OP_SB) String() string {
	return strings.Join([]string{"SB", o.imm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SB) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_SB) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SB) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SB) Opcode() opcodes.Opcode {
	return o.OP_SB
}

func (o OP_SB) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SB(IMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SB {

	return OP_SB{
		OP_SB: opcodes.OP_SB{
			IMM12: IMM12,
			RS1:   RS1,
			RS2:   RS2,
		},
		debug: debug,
	}
}

func DecodeSB(inst uint32) OP_SB {
	r := opcodes.OP_SB{}

	r.IMM12 = DEC_IMM12HILO(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)

	return OP_SB{
		OP_SB: r,
	}
}

type OP_SH struct {
	opcodes.OP_SH
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SH{}

func (o OP_SH) String() string {
	return strings.Join([]string{"SH", o.imm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SH) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_SH) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SH) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SH) Opcode() opcodes.Opcode {
	return o.OP_SH
}

func (o OP_SH) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SH(IMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SH {

	return OP_SH{
		OP_SH: opcodes.OP_SH{
			IMM12: IMM12,
			RS1:   RS1,
			RS2:   RS2,
		},
		debug: debug,
	}
}

func DecodeSH(inst uint32) OP_SH {
	r := opcodes.OP_SH{}

	r.IMM12 = DEC_IMM12HILO(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)

	return OP_SH{
		OP_SH: r,
	}
}

type OP_SW struct {
	opcodes.OP_SW
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SW{}

func (o OP_SW) String() string {
	return strings.Join([]string{"SW", o.imm12(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SW) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_SW) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SW) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SW) Opcode() opcodes.Opcode {
	return o.OP_SW
}

func (o OP_SW) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SW(IMM12 int32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SW {

	return OP_SW{
		OP_SW: opcodes.OP_SW{
			IMM12: IMM12,
			RS1:   RS1,
			RS2:   RS2,
		},
		debug: debug,
	}
}

func DecodeSW(inst uint32) OP_SW {
	r := opcodes.OP_SW{}

	r.IMM12 = DEC_IMM12HILO(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)

	return OP_SW{
		OP_SW: r,
	}
}

type OP_ADDI struct {
	opcodes.OP_ADDI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_ADDI{}

func (o OP_ADDI) String() string {
	return strings.Join([]string{"ADDI", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_ADDI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_ADDI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_ADDI) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_ADDI) Opcode() opcodes.Opcode {
	return o.OP_ADDI
}

func (o OP_ADDI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func ADDI(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_ADDI {

	return OP_ADDI{
		OP_ADDI: opcodes.OP_ADDI{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeADDI(inst uint32) OP_ADDI {
	r := opcodes.OP_ADDI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_ADDI{
		OP_ADDI: r,
	}
}

type OP_SLTI struct {
	opcodes.OP_SLTI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SLTI{}

func (o OP_SLTI) String() string {
	return strings.Join([]string{"SLTI", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_SLTI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SLTI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SLTI) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_SLTI) Opcode() opcodes.Opcode {
	return o.OP_SLTI
}

func (o OP_SLTI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SLTI(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_SLTI {

	return OP_SLTI{
		OP_SLTI: opcodes.OP_SLTI{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeSLTI(inst uint32) OP_SLTI {
	r := opcodes.OP_SLTI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_SLTI{
		OP_SLTI: r,
	}
}

type OP_SLTIU struct {
	opcodes.OP_SLTIU
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SLTIU{}

func (o OP_SLTIU) String() string {
	return strings.Join([]string{"SLTIU", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_SLTIU) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SLTIU) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SLTIU) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_SLTIU) Opcode() opcodes.Opcode {
	return o.OP_SLTIU
}

func (o OP_SLTIU) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SLTIU(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_SLTIU {

	return OP_SLTIU{
		OP_SLTIU: opcodes.OP_SLTIU{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeSLTIU(inst uint32) OP_SLTIU {
	r := opcodes.OP_SLTIU{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_SLTIU{
		OP_SLTIU: r,
	}
}

type OP_XORI struct {
	opcodes.OP_XORI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_XORI{}

func (o OP_XORI) String() string {
	return strings.Join([]string{"XORI", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_XORI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_XORI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_XORI) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_XORI) Opcode() opcodes.Opcode {
	return o.OP_XORI
}

func (o OP_XORI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func XORI(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_XORI {

	return OP_XORI{
		OP_XORI: opcodes.OP_XORI{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeXORI(inst uint32) OP_XORI {
	r := opcodes.OP_XORI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_XORI{
		OP_XORI: r,
	}
}

type OP_ORI struct {
	opcodes.OP_ORI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_ORI{}

func (o OP_ORI) String() string {
	return strings.Join([]string{"ORI", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_ORI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_ORI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_ORI) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_ORI) Opcode() opcodes.Opcode {
	return o.OP_ORI
}

func (o OP_ORI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func ORI(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_ORI {

	return OP_ORI{
		OP_ORI: opcodes.OP_ORI{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeORI(inst uint32) OP_ORI {
	r := opcodes.OP_ORI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_ORI{
		OP_ORI: r,
	}
}

type OP_ANDI struct {
	opcodes.OP_ANDI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_ANDI{}

func (o OP_ANDI) String() string {
	return strings.Join([]string{"ANDI", o.rd(), o.rs1(), o.imm12()}, " ")
}

func (o OP_ANDI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_ANDI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_ANDI) imm12() string {
	if o.IMM12 == 0 {
		return "imm12=0"
	} else {
		return fmt.Sprintf("imm12=%#x (%d)", uint64(o.IMM12), o.IMM12)
	}
}

func (o OP_ANDI) Opcode() opcodes.Opcode {
	return o.OP_ANDI
}

func (o OP_ANDI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func ANDI(RD uint32, RS1 uint32, IMM12 int32, debug debuginfo.DebugInfo) OP_ANDI {

	return OP_ANDI{
		OP_ANDI: opcodes.OP_ANDI{
			RD:    RD,
			RS1:   RS1,
			IMM12: IMM12,
		},
		debug: debug,
	}
}

func DecodeANDI(inst uint32) OP_ANDI {
	r := opcodes.OP_ANDI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.IMM12 = DEC_IMM12(inst)
	return OP_ANDI{
		OP_ANDI: r,
	}
}

type OP_ADD struct {
	opcodes.OP_ADD
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_ADD{}

func (o OP_ADD) String() string {
	return strings.Join([]string{"ADD", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_ADD) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_ADD) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_ADD) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_ADD) Opcode() opcodes.Opcode {
	return o.OP_ADD
}

func (o OP_ADD) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func ADD(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_ADD {

	return OP_ADD{
		OP_ADD: opcodes.OP_ADD{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeADD(inst uint32) OP_ADD {
	r := opcodes.OP_ADD{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_ADD{
		OP_ADD: r,
	}
}

type OP_SUB struct {
	opcodes.OP_SUB
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SUB{}

func (o OP_SUB) String() string {
	return strings.Join([]string{"SUB", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SUB) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SUB) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SUB) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SUB) Opcode() opcodes.Opcode {
	return o.OP_SUB
}

func (o OP_SUB) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SUB(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SUB {

	return OP_SUB{
		OP_SUB: opcodes.OP_SUB{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeSUB(inst uint32) OP_SUB {
	r := opcodes.OP_SUB{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_SUB{
		OP_SUB: r,
	}
}

type OP_SLL struct {
	opcodes.OP_SLL
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SLL{}

func (o OP_SLL) String() string {
	return strings.Join([]string{"SLL", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SLL) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SLL) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SLL) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SLL) Opcode() opcodes.Opcode {
	return o.OP_SLL
}

func (o OP_SLL) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SLL(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SLL {

	return OP_SLL{
		OP_SLL: opcodes.OP_SLL{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeSLL(inst uint32) OP_SLL {
	r := opcodes.OP_SLL{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_SLL{
		OP_SLL: r,
	}
}

type OP_SLT struct {
	opcodes.OP_SLT
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SLT{}

func (o OP_SLT) String() string {
	return strings.Join([]string{"SLT", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SLT) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SLT) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SLT) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SLT) Opcode() opcodes.Opcode {
	return o.OP_SLT
}

func (o OP_SLT) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SLT(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SLT {

	return OP_SLT{
		OP_SLT: opcodes.OP_SLT{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeSLT(inst uint32) OP_SLT {
	r := opcodes.OP_SLT{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_SLT{
		OP_SLT: r,
	}
}

type OP_SLTU struct {
	opcodes.OP_SLTU
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SLTU{}

func (o OP_SLTU) String() string {
	return strings.Join([]string{"SLTU", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SLTU) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SLTU) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SLTU) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SLTU) Opcode() opcodes.Opcode {
	return o.OP_SLTU
}

func (o OP_SLTU) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SLTU(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SLTU {

	return OP_SLTU{
		OP_SLTU: opcodes.OP_SLTU{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeSLTU(inst uint32) OP_SLTU {
	r := opcodes.OP_SLTU{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_SLTU{
		OP_SLTU: r,
	}
}

type OP_XOR struct {
	opcodes.OP_XOR
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_XOR{}

func (o OP_XOR) String() string {
	return strings.Join([]string{"XOR", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_XOR) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_XOR) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_XOR) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_XOR) Opcode() opcodes.Opcode {
	return o.OP_XOR
}

func (o OP_XOR) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func XOR(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_XOR {

	return OP_XOR{
		OP_XOR: opcodes.OP_XOR{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeXOR(inst uint32) OP_XOR {
	r := opcodes.OP_XOR{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_XOR{
		OP_XOR: r,
	}
}

type OP_SRL struct {
	opcodes.OP_SRL
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SRL{}

func (o OP_SRL) String() string {
	return strings.Join([]string{"SRL", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SRL) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SRL) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SRL) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SRL) Opcode() opcodes.Opcode {
	return o.OP_SRL
}

func (o OP_SRL) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SRL(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SRL {

	return OP_SRL{
		OP_SRL: opcodes.OP_SRL{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeSRL(inst uint32) OP_SRL {
	r := opcodes.OP_SRL{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_SRL{
		OP_SRL: r,
	}
}

type OP_SRA struct {
	opcodes.OP_SRA
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SRA{}

func (o OP_SRA) String() string {
	return strings.Join([]string{"SRA", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_SRA) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SRA) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SRA) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_SRA) Opcode() opcodes.Opcode {
	return o.OP_SRA
}

func (o OP_SRA) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SRA(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_SRA {

	return OP_SRA{
		OP_SRA: opcodes.OP_SRA{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeSRA(inst uint32) OP_SRA {
	r := opcodes.OP_SRA{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_SRA{
		OP_SRA: r,
	}
}

type OP_OR struct {
	opcodes.OP_OR
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_OR{}

func (o OP_OR) String() string {
	return strings.Join([]string{"OR", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_OR) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_OR) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_OR) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_OR) Opcode() opcodes.Opcode {
	return o.OP_OR
}

func (o OP_OR) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func OR(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_OR {

	return OP_OR{
		OP_OR: opcodes.OP_OR{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeOR(inst uint32) OP_OR {
	r := opcodes.OP_OR{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_OR{
		OP_OR: r,
	}
}

type OP_AND struct {
	opcodes.OP_AND
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_AND{}

func (o OP_AND) String() string {
	return strings.Join([]string{"AND", o.rd(), o.rs1(), o.rs2()}, " ")
}

func (o OP_AND) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_AND) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_AND) rs2() string {
	return fmt.Sprintf("rs2=x%d", o.RS2)
}

func (o OP_AND) Opcode() opcodes.Opcode {
	return o.OP_AND
}

func (o OP_AND) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func AND(RD uint32, RS1 uint32, RS2 uint32, debug debuginfo.DebugInfo) OP_AND {

	return OP_AND{
		OP_AND: opcodes.OP_AND{
			RD:  RD,
			RS1: RS1,
			RS2: RS2,
		},
		debug: debug,
	}
}

func DecodeAND(inst uint32) OP_AND {
	r := opcodes.OP_AND{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.RS2 = DEC_RS2(inst)
	return OP_AND{
		OP_AND: r,
	}
}

type OP_FENCE struct {
	opcodes.OP_FENCE
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_FENCE{}

func (o OP_FENCE) String() string {
	return strings.Join([]string{"FENCE", o.fm(), o.pred(), o.succ(), o.rs1(), o.rd()}, " ")
}

func (o OP_FENCE) fm() string {
	if o.FM == 0 {
		return "fm=0"
	} else {
		return fmt.Sprintf("fm=%#x (%d)", uint64(o.FM), o.FM)
	}
}

func (o OP_FENCE) pred() string {
	if o.PRED == 0 {
		return "pred=0"
	} else {
		return fmt.Sprintf("pred=%#x (%d)", uint64(o.PRED), o.PRED)
	}
}

func (o OP_FENCE) succ() string {
	if o.SUCC == 0 {
		return "succ=0"
	} else {
		return fmt.Sprintf("succ=%#x (%d)", uint64(o.SUCC), o.SUCC)
	}
}

func (o OP_FENCE) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_FENCE) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_FENCE) Opcode() opcodes.Opcode {
	return o.OP_FENCE
}

func (o OP_FENCE) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func FENCE(FM uint32, PRED uint32, SUCC uint32, RS1 uint32, RD uint32, debug debuginfo.DebugInfo) OP_FENCE {

	return OP_FENCE{
		OP_FENCE: opcodes.OP_FENCE{
			FM:   FM,
			PRED: PRED,
			SUCC: SUCC,
			RS1:  RS1,
			RD:   RD,
		},
		debug: debug,
	}
}

func DecodeFENCE(inst uint32) OP_FENCE {
	r := opcodes.OP_FENCE{}

	r.FM = DEC_FM(inst)
	r.PRED = DEC_PRED(inst)
	r.SUCC = DEC_SUCC(inst)
	r.RS1 = DEC_RS1(inst)
	r.RD = DEC_RD(inst)
	return OP_FENCE{
		OP_FENCE: r,
	}
}

type OP_ECALL struct {
	opcodes.OP_ECALL
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_ECALL{}

func (o OP_ECALL) String() string {
	return strings.Join([]string{"ECALL"}, " ")
}

func (o OP_ECALL) Opcode() opcodes.Opcode {
	return o.OP_ECALL
}

func (o OP_ECALL) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func ECALL(debug debuginfo.DebugInfo) OP_ECALL {

	return OP_ECALL{
		OP_ECALL: opcodes.OP_ECALL{},
		debug:    debug,
	}
}

func DecodeECALL(inst uint32) OP_ECALL {
	r := opcodes.OP_ECALL{}

	return OP_ECALL{
		OP_ECALL: r,
	}
}

type OP_EBREAK struct {
	opcodes.OP_EBREAK
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_EBREAK{}

func (o OP_EBREAK) String() string {
	return strings.Join([]string{"EBREAK"}, " ")
}

func (o OP_EBREAK) Opcode() opcodes.Opcode {
	return o.OP_EBREAK
}

func (o OP_EBREAK) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func EBREAK(debug debuginfo.DebugInfo) OP_EBREAK {

	return OP_EBREAK{
		OP_EBREAK: opcodes.OP_EBREAK{},
		debug:     debug,
	}
}

func DecodeEBREAK(inst uint32) OP_EBREAK {
	r := opcodes.OP_EBREAK{}

	return OP_EBREAK{
		OP_EBREAK: r,
	}
}

type OP_SLLI struct {
	opcodes.OP_SLLI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SLLI{}

func (o OP_SLLI) String() string {
	return strings.Join([]string{"SLLI", o.rd(), o.rs1(), o.shamtw()}, " ")
}

func (o OP_SLLI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SLLI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SLLI) shamtw() string {
	if o.SHAMTW == 0 {
		return "shamtw=0"
	} else {
		return fmt.Sprintf("shamtw=%#x (%d)", uint64(o.SHAMTW), o.SHAMTW)
	}
}

func (o OP_SLLI) Opcode() opcodes.Opcode {
	return o.OP_SLLI
}

func (o OP_SLLI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SLLI(RD uint32, RS1 uint32, SHAMTW uint32, debug debuginfo.DebugInfo) OP_SLLI {

	return OP_SLLI{
		OP_SLLI: opcodes.OP_SLLI{
			RD:     RD,
			RS1:    RS1,
			SHAMTW: SHAMTW,
		},
		debug: debug,
	}
}

func DecodeSLLI(inst uint32) OP_SLLI {
	r := opcodes.OP_SLLI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.SHAMTW = DEC_SHAMTW(inst)
	return OP_SLLI{
		OP_SLLI: r,
	}
}

type OP_SRLI struct {
	opcodes.OP_SRLI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SRLI{}

func (o OP_SRLI) String() string {
	return strings.Join([]string{"SRLI", o.rd(), o.rs1(), o.shamtw()}, " ")
}

func (o OP_SRLI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SRLI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SRLI) shamtw() string {
	if o.SHAMTW == 0 {
		return "shamtw=0"
	} else {
		return fmt.Sprintf("shamtw=%#x (%d)", uint64(o.SHAMTW), o.SHAMTW)
	}
}

func (o OP_SRLI) Opcode() opcodes.Opcode {
	return o.OP_SRLI
}

func (o OP_SRLI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SRLI(RD uint32, RS1 uint32, SHAMTW uint32, debug debuginfo.DebugInfo) OP_SRLI {

	return OP_SRLI{
		OP_SRLI: opcodes.OP_SRLI{
			RD:     RD,
			RS1:    RS1,
			SHAMTW: SHAMTW,
		},
		debug: debug,
	}
}

func DecodeSRLI(inst uint32) OP_SRLI {
	r := opcodes.OP_SRLI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.SHAMTW = DEC_SHAMTW(inst)
	return OP_SRLI{
		OP_SRLI: r,
	}
}

type OP_SRAI struct {
	opcodes.OP_SRAI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_SRAI{}

func (o OP_SRAI) String() string {
	return strings.Join([]string{"SRAI", o.rd(), o.rs1(), o.shamtw()}, " ")
}

func (o OP_SRAI) rd() string {
	return fmt.Sprintf("rd=x%d", o.RD)
}

func (o OP_SRAI) rs1() string {
	return fmt.Sprintf("rs1=x%d", o.RS1)
}

func (o OP_SRAI) shamtw() string {
	if o.SHAMTW == 0 {
		return "shamtw=0"
	} else {
		return fmt.Sprintf("shamtw=%#x (%d)", uint64(o.SHAMTW), o.SHAMTW)
	}
}

func (o OP_SRAI) Opcode() opcodes.Opcode {
	return o.OP_SRAI
}

func (o OP_SRAI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func SRAI(RD uint32, RS1 uint32, SHAMTW uint32, debug debuginfo.DebugInfo) OP_SRAI {

	return OP_SRAI{
		OP_SRAI: opcodes.OP_SRAI{
			RD:     RD,
			RS1:    RS1,
			SHAMTW: SHAMTW,
		},
		debug: debug,
	}
}

func DecodeSRAI(inst uint32) OP_SRAI {
	r := opcodes.OP_SRAI{}

	r.RD = DEC_RD(inst)
	r.RS1 = DEC_RS1(inst)
	r.SHAMTW = DEC_SHAMTW(inst)
	return OP_SRAI{
		OP_SRAI: r,
	}
}
