// AUTOGENERATED: DO NOT EDIT!
// Built from RISC-V ISA opcode definitions: https://github.com/riscv/riscv-opcodes

package disassemble

import (
	"fmt"
	"strings"

	"github.com/hawkowl/biscuit/pkg/debuginfo"
	"github.com/hawkowl/biscuit/pkg/opcodes"
)

type OP_MRET struct {
	opcodes.OP_MRET
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_MRET{}

func (o OP_MRET) String() string {
	return strings.Join([]string{"MRET"}, " ")
}

func (o OP_MRET) Opcode() opcodes.Opcode {
	return o.OP_MRET
}

func (o OP_MRET) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func MRET(debug debuginfo.DebugInfo) OP_MRET {

	return OP_MRET{
		OP_MRET: opcodes.OP_MRET{},
		debug:   debug,
	}
}

func DecodeMRET(inst uint32) OP_MRET {
	r := opcodes.OP_MRET{}

	return OP_MRET{
		OP_MRET: r,
	}
}

type OP_DRET struct {
	opcodes.OP_DRET
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_DRET{}

func (o OP_DRET) String() string {
	return strings.Join([]string{"DRET"}, " ")
}

func (o OP_DRET) Opcode() opcodes.Opcode {
	return o.OP_DRET
}

func (o OP_DRET) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func DRET(debug debuginfo.DebugInfo) OP_DRET {

	return OP_DRET{
		OP_DRET: opcodes.OP_DRET{},
		debug:   debug,
	}
}

func DecodeDRET(inst uint32) OP_DRET {
	r := opcodes.OP_DRET{}

	return OP_DRET{
		OP_DRET: r,
	}
}

type OP_WFI struct {
	opcodes.OP_WFI
	debug debuginfo.DebugInfo
}

var _ fmt.Stringer = OP_WFI{}

func (o OP_WFI) String() string {
	return strings.Join([]string{"WFI"}, " ")
}

func (o OP_WFI) Opcode() opcodes.Opcode {
	return o.OP_WFI
}

func (o OP_WFI) DebugInfo() debuginfo.DebugInfo {
	return o.debug
}

func WFI(debug debuginfo.DebugInfo) OP_WFI {

	return OP_WFI{
		OP_WFI: opcodes.OP_WFI{},
		debug:  debug,
	}
}

func DecodeWFI(inst uint32) OP_WFI {
	r := opcodes.OP_WFI{}

	return OP_WFI{
		OP_WFI: r,
	}
}
